Repository downshift-js/downshift, pull requests merged in 2020-06, with the labels that each got.

#1082 chore(tests): use expect.toHaveValue in tests
  src/hooks/useCombobox/__tests__/getInputProps.test.js
  src/hooks/useCombobox/__tests__/getItemProps.test.js
Labels: chore

#1083 fix(useCombobox): focus input after selection by click
  cypress/integration/useCombobox.js
  docs/tests/useCombobox.js
  docs/tests/useCombobox.mdx
  src/hooks/useCombobox/index.js
Labels: bug

#1090 chore(TS): accept null for selectedItem
  typings/index.d.ts
Labels: BREAKING CHANGE, TypeScript

#1075 fix(ts): specify that itemToString can receive null
  typings/index.d.ts
Labels: BREAKING CHANGE, TypeScript

#985 fix(hooks): add type to on change handler params
  src/hooks/useCombobox/__tests__/props.test.js
  src/hooks/useSelect/__tests__/props.test.js
  src/hooks/utils.js
  typings/index.d.ts
Labels: BREAKING CHANGE, TypeScript, bug
