Repository downshift-js/downshift, pull requests merged in 2020-07, with the labels that each got.

#1107 fix(useCombobox): fix onSelectedItemChange not triggering with controlled selectedItem in React.StrictMode
  src/hooks/useCombobox/__tests__/props.test.js
  src/hooks/useCombobox/utils.js
Labels: bug, wip

#1113 fix(useSelect): ensure the initial selected item is scrolled into view on first open
  src/hooks/useCombobox/__tests__/props.test.js
  src/hooks/useSelect/__tests__/props.test.js
  src/hooks/utils.js
Labels: bug, wip

#1104 downshift v6
  README.md
  src/__tests__/downshift.get-input-props.js
  src/downshift.js
  src/hooks/useCombobox/README.md
  src/hooks/useCombobox/__tests__/getInputProps.test.js
  src/hooks/useCombobox/__tests__/props.test.js
  src/hooks/useCombobox/index.js
  src/hooks/useCombobox/reducer.js
  src/hooks/useSelect/__tests__/props.test.js
  src/hooks/utils.js
  typings/index.d.ts
Labels: BREAKING CHANGE, TypeScript, wip

#1098 docs(useCombobox): proposal to add button type "button"
  docs/hooks/useCombobox.mdx
  src/hooks/useCombobox/README.md
Labels: docs

#1124 fix(Typescript): fix UseComboboxDispatchAction type
  README.md
  package.json
  typings/index.d.ts
Labels: TypeScript, bug
