Repository downshift-js/downshift, pull requests merged in 2020-08, with the labels that each got.

#1123 chore(Typescript): add type for the second argument of the appropriate getter props
  typings/index.d.ts
Labels: TypeScript, enhancement

#1135 docs(hooks): add getter prop ref documentation
  src/hooks/useCombobox/README.md
  src/hooks/useMultipleSelection/README.md
  src/hooks/useSelect/README.md
Labels: docs

#1143 docs: refresh the first part of the Readme and examples
  README.md
  src/hooks/useCombobox/README.md
  src/hooks/useMultipleSelection/README.md
  src/hooks/useSelect/README.md
Labels: docs

#1147 chore: update everything
  .size-snapshot.json
  package.json
  src/__tests__/downshift.aria.js
  src/__tests__/downshift.focus-restoration.js
  src/__tests__/downshift.get-input-props.js
  src/__tests__/downshift.get-item-props.js
  src/__tests__/downshift.get-label-props.js
  src/__tests__/downshift.get-root-props.js
  src/__tests__/downshift.lifecycle.js
  src/__tests__/downshift.misc-with-utils-mocked.js
  src/__tests__/portal-support.js
  src/__tests__/utils.reset-id-counter.js
  src/hooks/useCombobox/__tests__/getInputProps.test.js
  src/hooks/useCombobox/__tests__/getItemProps.test.js
  src/hooks/useCombobox/__tests__/getLabelProps.test.js
  src/hooks/useCombobox/__tests__/getToggleButtonProps.test.js
  src/hooks/useCombobox/testUtils.js
  src/hooks/useMultipleSelection/testUtils.js
  src/hooks/useSelect/__tests__/getItemProps.test.js
  src/hooks/useSelect/__tests__/getLabelProps.test.js
  src/hooks/useSelect/__tests__/getMenuProps.test.js
  src/hooks/useSelect/__tests__/getToggleButtonProps.test.js
  src/hooks/useSelect/__tests__/props.test.js
  src/hooks/useSelect/testUtils.js
Labels: chore

#1154 docs: update downshift logo link
  README.md
Labels: docs

#1165 docs: update references to examples and docs
  README.md
  package.json
  src/hooks/useCombobox/README.md
  src/hooks/useMultipleSelection/README.md
  src/hooks/useSelect/README.md
Labels: docs

#1153 docs(useSelect): add button type "button" to useSelect docs
  src/hooks/useSelect/README.md
Labels: docs
